apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: garage
  name: garage-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garage-rolebinding
  namespace: garage
subjects:
- kind: User
  name: "rajaeamal301024"  # Change this to your username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: garage-role
  apiGroup: rbac.authorization.k8s.io
