apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: garage
type: Opaque
data:
  DB_USER: cm9vdA==    # base64 encoded value of "root"
  DB_PASS: c2Vra2F0    # base64 encoded value of "sekkat"
  MYSQL_ROOT_PASSWORD: c2Vra2F0 # base64 encoded value of "sekkat"
